ASFLAGS := $(KBUILD_CFLAGS)

# all: $(output_dir)/liblib.a

obj-y := string.o vsprintf.o
#obj-y := $(addprefix $(output_dir)/, $(obj-y))
# lib: $(lib-y)

# $(output_dir)/liblib.a: $(lib-y)
#	$(AR) -rcs $@ $(lib-y)

